name: ForceChat
main: io.github.com.geertbraakman.ForceChat
version: '2.0.1'
description: 'An easy to use forcechat plugin, use the command /forcechat.'
softdepend:
  - PlaceholderAPI
author: x313
website: https://www.spigotmc.org/resources/forcechat.52014/
